name: Update Last Modified Date

on:
  push:
    branches:
      - master

jobs:
  update-last-modified-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Last Modified Date
        run: |
          sed -i "s/<h4>Last Modified: .*<\/h4>/<h4>Last Modified: $(date '+%dth %B, %Y')<\/h4>/" index.html


      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -am "Update last modified date [skip ci]"
          git push
